package by.news.controller;

public enum CommandName {
	REGISTRATION, AUTHORIZATION, REGISTRATION_NEW_USER, GO_TO_MAIN_PAGE, SIGN_IN, LOG_OUT, CHANGE_LOCALE, READ_NEWS,
	ADD_NEWS, UPDATE_NEWS, DELETE_NEWS, APPROVE_PROPOSED_NEWS, RESTORE_DELETED_NEWS, GO_TO_AUTH_USER_PAGE,
	GO_TO_ADDING_NEWS_PAGE, GO_TO_UPDATING_NEWS_PAGE, GO_TO_PROPOSED_NEWS_PAGE, GO_TO_DELETED_NEWS_PAGE,
	UNKNOWN_COMMAND;

}
